name: CI

on:
  workflow_dispatch:

jobs:
  build-mac-win:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macOS-latest, windows-latest ]
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10' ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Setup Rust environment
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Setup Python environment
        uses: actions/setup-python@v2.1.4
        with:
          python-version: ${{ matrix.python-version }}
      - name: maturin build --release
        run: |
          pip install --upgrade pip
          pip install maturin
          maturin build --release --cargo-extra-args="--features pyo3"
      - uses: actions/upload-artifact@v1
        name: upload-wheel
        with:
          name: wheel-${{ matrix.platform }}-${{ matrix.python-version }}
          path: target/wheels/
      - name: Publish to PyPI
        if: github.event_name == 'workflow_dispatch'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install --upgrade twine
          twine upload --skip-existing target/wheels/*
  build-manylinux2010:
    runs-on: ubuntu-latest
    container: konstin2/maturin:latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Setup Rust environment
        run: |
          rustup default stable
      - name: maturin build --release
        run: |
          pip install --upgrade pip
          maturin build --release --cargo-extra-args="--features pyo3"
      - uses: actions/upload-artifact@v1
        name: upload-wheel
        with:
          name: wheel-manylinux2010
          path: target/wheels/
      - name: Publish to PyPI
        if: github.event_name == 'workflow_dispatch'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install --upgrade twine
          twine upload --skip-existing target/wheels/*